/*
 * This source file was generated by the Gradle 'init' task
 */
package com.ntunghoi.tutorials.oauth2;

import org.junit.jupiter.api.Test;

class TokenExchangeAppTest {
    @Test
    void appHasAGreeting() {
        
    }
}
