/*
 * This source file was generated by the Gradle 'init' task
 */
package com.ntunghoi.tutorials.oauth2;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.security.oauth2.client.autoconfigure.OAuth2ClientAutoConfiguration;

@SpringBootApplication(exclude = {
        OAuth2ClientAutoConfiguration.class
})
public class TokenExchangeApp {
    static void main(String[] args) {
        SpringApplication.run(TokenExchangeApp.class, args);
    }
}
