/*
 * This source file was generated by the Gradle 'init' task
 */
package com.ntunghoi.tutorials.oauth2;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class TokenExchangeApp {
    static void main(String[] args) {
        SpringApplication.run(TokenExchangeApp.class, args);
    }
}
