/*
 * This source file was generated by the Gradle 'init' task
 */
package com.ntunghoi.tutorials;

import com.ntunghoi.tutorials.oauth2.TokenExchangeApp;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void appHasAGreeting() {
        TokenExchangeApp classUnderTest = new TokenExchangeApp();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
