spring:
  datasource:
    url: jdbc:postgresql//localhost:5432/java_tutorials?currentSchema=token_exchange
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    user:
      name: admin
      password: password
      roles: ADMIN
    oauth2:
      authorizationserver:
        client:
          my-client:
            registration:
              client-id: my-client
              client-secret: "{noop}my-secret"
              client-authentication-methods:
                - client_secret_basic
              authorization-grant-types:
                - authorization_code
                - refresh_token
                - client_credentials
              redirect-uris:
                - "http://127.0.0.1:8080/login/oauth2/code/my-client"
              scopes:
                - openid
                - profile
                - read
              require-authorization-consent: true
server:
  port: 8080
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG